# Generated by Django 3.1.3 on 2020-11-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201030_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Own',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=500)),
                ('game_link', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Game',
            new_name='Game_Fav',
        ),
    ]
