# Generated by Django 3.1.1 on 2021-01-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20201121_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_fav',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='game_own',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
