# Generated by Django 3.2.7 on 2021-09-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("notification_name", models.CharField(default="", max_length=50)),
                ("notification_text", models.CharField(default="", max_length=300)),
            ],
        ),
    ]
