# Generated by Django 3.1.6 on 2021-04-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game_Fav",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=500)),
                ("game_link", models.CharField(max_length=500)),
                ("desc", models.CharField(max_length=5000)),
                ("image", models.ImageField(default="", upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Game_Own",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_name", models.CharField(max_length=500)),
                ("game_link", models.CharField(max_length=500)),
                ("desc", models.CharField(max_length=5000)),
                ("image", models.ImageField(default="", upload_to="")),
            ],
        ),
    ]
