# Generated by Django 3.1.7 on 2021-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210407_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_fav',
            name='image',
            field=models.ImageField(default='', upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='game_own',
            name='image',
            field=models.ImageField(default='', upload_to='static/image'),
        ),
    ]
