# Generated by Django 3.1.7 on 2021-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210411_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_fav',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
        migrations.AddField(
            model_name='game_own',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
