# Generated by Django 3.1.7 on 2021-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210411_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_photo',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
