# Generated by Django 3.1.7 on 2021-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_notfication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notfication',
            name='notification_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
