# Generated by Django 3.1.7 on 2021-04-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0015_auto_20210429_1827"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notfication",
            new_name="Notification",
        ),
    ]
