# Generated by Django 3.1.7 on 2021-05-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_auto_20210429_2214"),
    ]

    operations = [
        migrations.CreateModel(
            name="My_Photo_Permission_Grant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(default="", max_length=70)),
                ("desc", models.CharField(default="", max_length=500)),
            ],
        ),
    ]
