# Generated by Django 3.1.7 on 2021-04-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20210429_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_has_readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(db_index=True, default=''),
        ),
    ]
