# Generated by Django 3.1.7 on 2021-05-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20210507_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_photo_permission_grant',
            options={},
        ),
    ]
