# Generated by Django 3.1.7 on 2021-04-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210430_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
