# Generated by Django 3.1.7 on 2021-05-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210507_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_Photo_Permission_Grant',
        ),
    ]
