# Generated by Django 3.1.7 on 2021-04-30 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20210430_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
    ]
