# Generated by Django 3.1.7 on 2021-05-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_auto_20210507_1506"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="my_photo",
            options={},
        ),
    ]
