# Generated by Django 3.1.6 on 2021-04-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_notification_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_has_readed',
        ),
    ]
