# Generated by Django 3.1.7 on 2021-05-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0023_youtubevideos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YouTubeVideos",
            new_name="YouTubeVideo",
        ),
    ]
