# Generated by Django 3.1.7 on 2021-06-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0026_auto_20210527_1022"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YouTubeVideo",
            new_name="Youtube_Video",
        ),
    ]
