# Generated by Django 3.2.7 on 2021-09-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0028_auto_20210827_1503"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Youtube_Video",
        ),
    ]
