# Generated by Django 3.2.7 on 2021-09-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0029_delete_youtube_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
