# Generated by Django 3.2.8 on 2021-11-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_fav',
            name='image',
            field=models.ImageField(default='', upload_to='images/game_fav'),
        ),
        migrations.AlterField(
            model_name='game_own',
            name='image',
            field=models.ImageField(default='', upload_to='images/game_fav'),
        ),
        migrations.AlterField(
            model_name='my_photo',
            name='image',
            field=models.ImageField(default='', upload_to='images/my_photots'),
        ),
    ]
