# Generated by Django 3.2.8 on 2022-01-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(default="", max_length=70)),
                ("phone", models.CharField(default="", max_length=70)),
                ("desc", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Game_Fav",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                ("link", models.CharField(default="", max_length=500)),
                ("desc", models.TextField(default="")),
                ("image", models.ImageField(default="", upload_to="images/games/fav")),
            ],
        ),
        migrations.CreateModel(
            name="Game_Own",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                ("link", models.CharField(default="", max_length=500)),
                ("desc", models.TextField(default="")),
                ("image", models.ImageField(default="", upload_to="images/games/own")),
            ],
        ),
        migrations.CreateModel(
            name="My_Photo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=50)),
                ("image", models.ImageField(default="", upload_to="images/my_photos")),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=50)),
                ("text", models.TextField(default="")),
            ],
        ),
    ]
