# Generated by Django 3.2.18 on 2023-07-29 10:34

import django.contrib.postgres.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='images/projects/')),
                ('link', models.CharField(default='', max_length=100)),
                ('source_code', models.CharField(blank=True, default='', max_length=100)),
                ('tech_stack', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=list, size=None)),
            ],
        ),
    ]
