# Generated by Django 3.2.8 on 2022-01-31 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game_fav',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game_own',
            old_name='desc',
            new_name='description',
        ),
    ]
