# Generated by Django 3.2.8 on 2022-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_auto_20220131_0857"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(default="", max_length=10),
        ),
    ]
