# Generated by Django 3.2.8 on 2022-02-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_alter_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_photo",
            name="height",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AddField(
            model_name="my_photo",
            name="width",
            field=models.CharField(default="", max_length=5),
        ),
    ]
