# Generated by Django 3.2.18 on 2023-07-15 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
