# Generated by Django 3.2.18 on 2023-07-16 15:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=list, size=None),
        ),
    ]
