# Generated by Django 3.2.12 on 2022-04-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_auto_20220404_2100"),
    ]

    operations = [
        migrations.DeleteModel(
            name="My_Photo",
        ),
    ]
